package scxmlgen.Modalities;

import scxmlgen.interfaces.IOutput;



public enum Output implements IOutput{

    // Speech Outputs
    // Search & Navigation
    SEARCH_LOCATION("[FUSION][SEARCH_LOCATION]"),
    GET_DIRECTIONS("[FUSION][GET_DIRECTIONS]"),
    START_NAVIGATION("[FUSION][START_NAVIGATION]"),
    STOP_NAVIGATION("[FUSION][STOP_NAVIGATION]"),

    // Map Controls
    ZOOM_IN("[FUSION][ZOOM_IN]"),
    ZOOM_OUT("[FUSION][ZOOM_OUT]"),
    CHANGE_MAP_TYPE("[FUSION][CHANGE_MAP_TYPE]"),
    RECENTER_MAP("[FUSION][RECENTER_MAP]"),
    CENTER_LOCATION("[FUSION][CENTER_LOCATION]"),
    SHOW_TRAFFIC("[FUSION][SHOW_TRAFFIC]"),
    HIDE_TRAFFIC("[FUSION][HIDE_TRAFFIC]"),

    // Trip Information
    GET_TRIP_DURATION("[FUSION][GET_TRIP_DURATION]"),
    GET_TRIP_DISTANCE("[FUSION][GET_TRIP_DISTANCE]"),
    CHANGE_TRANSPORT_MODE("[FUSION][CHANGE_TRANSPORT_MODE]"),
    SWAP_ROUTE("[FUSION][SWAP_ROUTE]"),

    // Place Selection
    SELECT_PLACE("[FUSION][SELECT_PLACE]"),
    SELECT_ALTERNATIVE_ROUTE("[FUSION][SELECT_ALTERNATIVE_ROUTE]"),

    // Location Information
    SHOW_PLACE_DETAILS("[FUSION][SHOW_PLACE_DETAILS]"),
    GET_LOCATION_INFO("[FUSION][GET_LOCATION_INFO]"),
    SHOW_REVIEWS("[FUSION][SHOW_REVIEWS]"),
    SHOW_PHOTOS("[FUSION][SHOW_PHOTOS]"),
    GET_OPENING_HOURS("[FUSION][GET_OPENING_HOURS]"),
    WHATS_HERE("[FUSION][WHATS_HERE]"),

    // Conversational
    HELP("[FUSION][HELP]"),
    CANCEL("[FUSION][CANCEL]"),
    THANKS("[FUSION][THANKS]"),

    // Gesture Outputs
    // Map Filters
    GESTURE_RESTAURANTS("[FUSION][GESTURE_RESTAURANTS]"),
    GESTURE_HOTELS("[FUSION][GESTURE_HOTELS]"),
    GESTURE_GAS_STATIONS("[FUSION][GESTURE_GAS_STATIONS]"),
    GESTURE_TRANSPORTS("[FUSION][GESTURE_TRANSPORTS]"),

    // Map Navigation
    GESTURE_SWIPE_LEFT("[FUSION][GESTURE_SWIPE_LEFT]"),
    GESTURE_SWIPE_RIGHT("[FUSION][GESTURE_SWIPE_RIGHT]"),
    GESTURE_SWIPE_UP("[FUSION][GESTURE_SWIPE_UP]"),
    GESTURE_SWIPE_DOWN("[FUSION][GESTURE_SWIPE_DOWN]"),
    GESTURE_ZOOM_IN("[FUSION][GESTURE_ZOOM_IN]"),
    GESTURE_ZOOM_OUT("[FUSION][GESTURE_ZOOM_OUT]"),

    // Street View
    GESTURE_ENTER_STREET("[FUSION][GESTURE_ENTER_STREET]"),
    GESTURE_EXIT_STREET("[FUSION][GESTURE_EXIT_STREET]"),
    GESTURE_FORWARD("[FUSION][GESTURE_FORWARD]"),
    GESTURE_CAMERA("[FUSION][GESTURE_CAMERA]"),

    // List Navigation
    GESTURE_SELECT("[FUSION][GESTURE_SELECT]"),
    GESTURE_UP_OPTION("[FUSION][GESTURE_UP_OPTION]"),
    GESTURE_DOWN_OPTION("[FUSION][GESTURE_DOWN_OPTION]")
    ;
    
    
    
    private String event;

    Output(String m) {
        event=m;
    }
    
    public String getEvent(){
        return this.toString();
    }

    public String getEventName(){
        return event;
    }
}
