package Modalities;

import scxmlgen.interfaces.IOutput;



public enum Output implements IOutput{


    ZOOM_IN_UP("[FUSION][ZOOM_IN_UP]"),
    ZOOM_IN_DOWN("[FUSION][ZOOM_IN_DOWN]"),
    ZOOM_IN_LEFT("[FUSION][ZOOM_IN_LEFT]"),
    ZOOM_IN_RIGHT("[FUSION][ZOOM_IN_RIGHT]"),
    ZOOM_OUT_UP("[FUSION][ZOOM_OUT_UP]"),
    ZOOM_OUT_DOWN("[FUSION][ZOOM_OUT_DOWN]"),
    ZOOM_OUT_LEFT("[FUSION][ZOOM_OUT_LEFT]"),
    ZOOM_OUT_RIGHT("[FUSION][ZOOM_OUT_RIGHT]"),

    // New Complementary Fusion Outputs
    DIRECTIONS_PUBLIC_TRANSPORT("[FUSION][DIRECTIONS_PUBLIC_TRANSPORT]"),
    TRAFFIC_OVERVIEW("[FUSION][TRAFFIC_OVERVIEW]"),
    FILTER_RESTAURANTS_CENTER("[FUSION][FILTER_RESTAURANTS_CENTER]"),
    STREET_VIEW_FORWARD_CONTINUOUS("[FUSION][STREET_VIEW_FORWARD_CONTINUOUS]"),

    // Speech Outputs
    // Search & Navigation
    SEARCH_LOCATION("[SPEECH][SEARCH_LOCATION]"),
    GET_DIRECTIONS("[SPEECH][GET_DIRECTIONS]"),
    START_NAVIGATION("[SPEECH][START_NAVIGATION]"),
    STOP_NAVIGATION("[SPEECH][STOP_NAVIGATION]"),

    // Map Controls
    ZOOM_IN("[SPEECH][ZOOM_IN]"),
    ZOOM_OUT("[SPEECH][ZOOM_OUT]"),
    CHANGE_MAP_TYPE("[SPEECH][CHANGE_MAP_TYPE]"),
    RECENTER_MAP("[SPEECH][RECENTER_MAP]"),
    CENTER_LOCATION("[SPEECH][CENTER_LOCATION]"),
    SHOW_TRAFFIC("[SPEECH][SHOW_TRAFFIC]"),
    HIDE_TRAFFIC("[SPEECH][HIDE_TRAFFIC]"),

    // Trip Information
    GET_TRIP_DURATION("[SPEECH][GET_TRIP_DURATION]"),
    GET_TRIP_DISTANCE("[SPEECH][GET_TRIP_DISTANCE]"),
    CHANGE_TRANSPORT_MODE("[SPEECH][CHANGE_TRANSPORT_MODE]"),
    SWAP_ROUTE("[SPEECH][SWAP_ROUTE]"),

    // Place Selection
    SELECT_PLACE("[SPEECH][SELECT_PLACE]"),
    SELECT_ALTERNATIVE_ROUTE("[SPEECH][SELECT_ALTERNATIVE_ROUTE]"),

    // Location Information
    SHOW_PLACE_DETAILS("[SPEECH][SHOW_PLACE_DETAILS]"),
    GET_LOCATION_INFO("[SPEECH][GET_LOCATION_INFO]"),
    SHOW_REVIEWS("[SPEECH][SHOW_REVIEWS]"),
    SHOW_PHOTOS("[SPEECH][SHOW_PHOTOS]"),
    GET_OPENING_HOURS("[SPEECH][GET_OPENING_HOURS]"),
    WHATS_HERE("[SPEECH][WHATS_HERE]"),

    // Conversational
    HELP("[SPEECH][HELP]"),
    CANCEL("[SPEECH][CANCEL]"),
    THANKS("[SPEECH][THANKS]"),

    // Gesture Outputs
    // Map Filters
    GESTURE_RESTAURANTS("[GESTURES][GESTURE_RESTAURANTS]"),
    GESTURE_HOTELS("[GESTURES][GESTURE_HOTELS]"),
    GESTURE_GAS_STATIONS("[GESTURES][GESTURE_GAS_STATIONS]"),
    GESTURE_TRANSPORTS("[GESTURES][GESTURE_TRANSPORTS]"),

    // Map Navigation
    GESTURE_SWIPE_LEFT("[GESTURES][GESTURE_SWIPE_LEFT]"),
    GESTURE_SWIPE_RIGHT("[GESTURES][GESTURE_SWIPE_RIGHT]"),
    GESTURE_SWIPE_UP("[GESTURES][GESTURE_SWIPE_UP]"),
    GESTURE_SWIPE_DOWN("[GESTURES][GESTURE_SWIPE_DOWN]"),
    GESTURE_ZOOM_IN("[GESTURES][GESTURE_ZOOM_IN]"),
    GESTURE_ZOOM_OUT("[GESTURES][GESTURE_ZOOM_OUT]"),

    // Street View
    GESTURE_ENTER_STREET("[GESTURES][GESTURE_ENTER_STREET]"),
    GESTURE_EXIT_STREET("[GESTURES][GESTURE_EXIT_STREET]"),
    GESTURE_FORWARD("[GESTURES][GESTURE_FORWARD]"),
    GESTURE_CAMERA("[GESTURES][GESTURE_CAMERA]"),

    // List Navigation
    GESTURE_SELECT("[GESTURES][GESTURE_SELECT]"),
    GESTURE_UP_OPTION("[GESTURES][GESTURE_UP_OPTION]"),
    GESTURE_DOWN_OPTION("[GESTURES][GESTURE_DOWN_OPTION]")
    ;
    
    
    
    private String event;

    Output(String m) {
        event=m;
    }
    
    public String getEvent(){
        return this.toString();
    }

    public String getEventName(){
        return event;
    }
}
