/* 
  *   Speech.java generated by speechmod 
 */   

package Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{

	// Search & Navigation
	SEARCH_LOCATION("[SPEECH][SEARCH_LOCATION]", 1500),
	GET_DIRECTIONS("[SPEECH][GET_DIRECTIONS]", 2500),
	START_NAVIGATION("[SPEECH][START_NAVIGATION]", 2500),
	STOP_NAVIGATION("[SPEECH][STOP_NAVIGATION]", 1500),

	// Map Controls
	ZOOM_IN("[SPEECH][ZOOM_IN]", 2500),
	ZOOM_OUT("[SPEECH][ZOOM_OUT]", 2500),
	CHANGE_MAP_TYPE("[SPEECH][CHANGE_MAP_TYPE]", 1500),
	RECENTER_MAP("[SPEECH][RECENTER_MAP]", 2500),
	CENTER_LOCATION("[SPEECH][CENTER_LOCATION]", 1500),
	SHOW_TRAFFIC("[SPEECH][SHOW_TRAFFIC]", 2500),
	HIDE_TRAFFIC("[SPEECH][HIDE_TRAFFIC]", 1500),

	// Trip Information
	GET_TRIP_DURATION("[SPEECH][GET_TRIP_DURATION]", 1500),
	GET_TRIP_DISTANCE("[SPEECH][GET_TRIP_DISTANCE]", 1500),
	CHANGE_TRANSPORT_MODE("[SPEECH][CHANGE_TRANSPORT_MODE]", 1500),
	SWAP_ROUTE("[SPEECH][SWAP_ROUTE]", 1500),

	// Place Selection
	SELECT_PLACE("[SPEECH][SELECT_PLACE]", 1500),
	SELECT_ALTERNATIVE_ROUTE("[SPEECH][SELECT_ALTERNATIVE_ROUTE]", 1500),

	// Location Information
	SHOW_PLACE_DETAILS("[SPEECH][SHOW_PLACE_DETAILS]", 1500),
	GET_LOCATION_INFO("[SPEECH][GET_LOCATION_INFO]", 1500),
	SHOW_REVIEWS("[SPEECH][SHOW_REVIEWS]", 1500),
	SHOW_PHOTOS("[SPEECH][SHOW_PHOTOS]", 1500),
	GET_OPENING_HOURS("[SPEECH][GET_OPENING_HOURS]", 1500),
	WHATS_HERE("[SPEECH][WHATS_HERE]", 1500),

	// Conversational
	HELP("[SPEECH][HELP]", 1500),
	CANCEL("[SPEECH][CANCEL]", 1500),
	THANKS("[SPEECH][THANKS]", 1500);


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
